CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255)        NOT NULL,
    email VARCHAR(512) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    available   BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id    BIGINT       NOT NULL,
    request     VARCHAR(512),
    CONSTRAINT fk_items_owner FOREIGN KEY (owner_id)
        REFERENCES users (id) ON DELETE CASCADE
);

--индексы
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_items_owner_id ON items (owner_id);
CREATE INDEX IF NOT EXISTS idx_items_available ON items (available);