server:
  port: 8080

shareit-server:
  url: "http://localhost:9090"

spring:
  cache:
    cache-names:
    - "itemsCache"
    - "usersCache"
    - "bookingsCache"
    - "searchCache"
    - "itemRequestsCache"

    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m
